### ISSUE TITLE
More info about installation document

### ISSUE THREAD

**Issue by JuliusChen** [Mirantis/ceph-lcm#63]
Hi,
Could you offer more info about ceph-lcm installation. I could run vagrant up and ansible,
but it also stop at npm install (no root permission), what step should I follow to resolve this problem.
And after installation, Is there any operation guide I could know this deploy tool better?

Really appreciated for your help, Thanks.

**Comment by 9seconds** [comment]
Hi,

https://docs.google.com/document/d/1tqAWVLZKK7L2etxEkIL0BFSVgFZkXUjFbEGEzncVMuQ/edit could you please check this document? It describes problems you've been faced with. And I hope it has possible solutions.

**Comment by 9seconds** [comment]
I am closing this issue. If you have any questions, please feel free to open again.

**Comment by JuliusChen** [comment]
Sure, Thanks for help and provide this document. The Ceph-lcm UI ip what this document mentioned is
10.10.0.2:9999, but when using command 'docker inspect "ceph-lcm shirmp UI container ID"' it may be different with 10.10.0.2:9999. Could this change update to this document and also thanks your reply.

Sincerely.
